### ISSUE TITLE
Todo week 2

### ISSUE THREAD

**Issue by dioptre** [mceoin/galacticWiki#3]
# Now:
- [ ] due diligence of existing products @mceoin 
- [ ] prove download authors/bloggers
- [ ] crawl all bloggers and newswriters on the internet
- [ ] extract author

# Later:
- [ ] get email/twitter of author

**Comment by mceoin** [comment]
Result: Product killed in Due Diligence.

We did learn how to use common crawl to search for "anything" and get a list of URLs that have that thing, or extract a big list of it from the web.
