### ISSUE TITLE
Todo week 3

### ISSUE THREAD

**Issue by mceoin** [mceoin/galacticWiki#4]
# Technical setup
- [ ] investigate the internet for an A/B testing solution so you can automate most of this
- [ ] Google ads
- [ ] Facebook ads
- [ ] Linkedin Ads
- [ ] Landing pages
- [ ] Craigslist ads
- [ ] Find the best "close to instant meeting" process you can find without developing anything and share it with each other
- [ ] Brainstorm market targets, then go off by yourselves and compete

# Process (Do this initially together, and then by yourselves after 2 days)
- [ ] Determine how to get someone in the funnel
- [ ] Get them to act (commit to video chat)
- [ ] Coordination: Get them into actual video chat.
- [ ] Learn how to create a good video-chat experience. 
- [ ] Accept $
- [ ] Close feedback loop (ask for feedback, etc.), and test best response (Ex. Recommend friend)

# Market Areas
- [ ] >10 Segments, >10 Landing pages
- [ ] Quantify market response (% ads, clickthrough, response from landing page, how much will people pay?)

# Learning Goal
- [ ] Can you validate a p2p realtime help idea end to end?

**Comment by dioptre** [comment]
Killed by Jonathan
