### ISSUE TITLE
Todo Week 4

### ISSUE THREAD

**Issue by dioptre** [mceoin/galacticWiki#6]
# Eoin
- [ ] DD on product
- [ ] Runthrough
- [ ] Test/Validate/Kill (We need data. $ and opportunity)

# Jeff
- [ ] Provide a 1 week and 2 week sprint plan for POC
- [ ] Make POC
